import { Mentor } from "../../assets";
const teams = [
  {
    teamName: "Faculty Mentors",
    members: [
      {
        name: "Dr. Saji M Antony",
        designation:
            "Associate Professor, Dept. of ECE, BVCOE",
        linkedin: "",
        instagram: "https://www.instagram.com/edu_minerva/",
        optionalLink: "",
        picLink: Mentor,
      },
    ],
  },
    //Core Team
  {
    teamName: "Core Team",
    members: [
      {
        name: "Devansh Singhal",
        designation: "President",
        linkedin: "",
        instagram: "https://www.instagram.com/_devansh_singhal_/",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1UtZx9bVEE2hz0NZwLMq3IIRStd-XSYvS&sz=w1000",
      },
      {
        name: "Advait Jain",
        designation: "Vice-President",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/uc?export=view&id=145mGSOuTWefhVgW4Q2vxVIqT3idrZjKG",
      },
      {
        name: "Mohit Bhushan",
        designation: "Vice-President",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1T2IJF5QnsvBQuOlfsm916ldsRNyo0SFK&sz=w1000",
      },
      {
        name: "Lakshay",
        designation: "President EduTech",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1WgVCsArygDQYuG6zOB6owEbdK4HsxDvZ&sz=w1000",
      },
      {
        name: "Arnav Goel",
        designation: "Joint Secretary",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=15w6hQK3VaPQgoyS7uaz5UvLNT9k9O4SM&sz=w1000",
      },
      {
        name: "Riya Sharma",
        designation: "Joint Secretary",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1Fl0v1--YKhSz-PQ-sm5aSzo7wzKnUeFf&sz=w1000",
      },
      {
        name: "Armaan Jain",
        designation: "Creative Lead",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1K0EWAQorH7Y_Jx_X8bxamaDEZtetD54M&sz=w1000",
      },
      {
        name: "Khushi Nagpal",
        designation: "Treasurer",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1sL5YsMv4J0dSlHyDbyaOt9MaiGe6qIrd&sz=w1000",
      },
      {
        name: "Mohit Lamba",
        designation: "Tech Lead",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1qX66rEwSkWfBpP9euKNWe2zpTtLCyLJq&sz=w1000",
      }
    ],
  },
    //Technical Team
  {
    teamName: "Technical",
    members: [
      {
        name: "Shresth Agarwal",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1_ZxRen4YJpmV5jaSzz4EpnmFix4u5QPt&sz=w1000"
      },
      {
        name: "Shivank Aggarwal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1v6iVVvo8mnsR4An4-N47UxHQl95XlcEH&sz=w1000",
      },
      {
        name: "Rishi Kumar Nayak",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1_9J8meqp76rTqfJAZoz9TGask-RMdGXu&sz=w1000",
      },
      {
        name: "Sanskar Kannaujia",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1B0XWfbttjeK0OTbG9ybZIrucjPcHVnCx&sz=w1000",
      },
      {
        name: "Kartik Padaliya",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=18haIWSM7m7EuzaEpDpUnalXNwGJBlCeW&sz=w1000",
      },
      {
        name: "Shashank Gupta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1-CkWLVHRs4CVWJYqcKWB-uSSwUL4fuwv&sz=w1000",
      },
      {
        name: "Shivam Jindal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1mT4zDVhVD8g_c4YgfRyEVAVtd6OeTqgH&sz=w1000",
      },
      {
        name: "Satvik Phour",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1ZwuF3DaH5KrySOUck8c8wvYEGMsrk89S&sz=w1000",
      },
      {
        name: "Diptesh Pradhan",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=15e4mF8mhQ9cbW2W6bRvLaLapaS6cpq-c&sz=w1000",
      },
      {
        name: "Parisha Sheoran",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1RFPOfv-fWx6-QNoVpezZYcRKNUbxHiSX&sz=w1000",
      },
      {
        name: "Sachin Negi",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1Q6g1Y2R1BFXgXBG4BQgspxLuJ7lSeWry&sz=w1000",
      }
    ],
  },
    //Content and Documentation
  {
    teamName: "Content & Documentation",
    members: [
      {
        name: "Divyansh Singh",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1FNGTOH-cXoIfkE3nfWSAFmOO_1wJrA2l&sz=w1000",
      },
      {
        name: "Sneha",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1KR1cTOlUx-Ld80M8_CzajGy-dLP2b6xD&sz=w1000",
      },
      {
        name: "Anushka Gupta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1boNf6BAedddwX0ZXyOdGL8oYGCH0fBK4&sz=w1000",
      },
      {
        name: "Alok Tripathi",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=10nJLkFQMUaNp_uS0GkM4IEFHU1foURdd&sz=w1000",
      },
      {
        name: "Manya Sharma",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1IVRqtLlj3Er-FzQZvMEbn0dU1LVi0R5W&sz=w1000",
      },
      {
        name: "Harshita Bhasin",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1rRKXccC9OtwFALdSg_5PPMaGhQeHgI0y&sz=w1000",
      },
      {
        name: "Diya Yadav",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1flFVm2h9WPa4VJRa8bLwRIifhC2zO69I&sz=w1000",
      },
      {
        name: "Piyush Singh",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1UYgyvdLlsX6G1_GWYSoHfCyXFGZ2DWNX&sz=w1000",
      },
      {
        name: "Garima Sharma",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=16Yk4A4Q11mdjR2FtxguIrIncyZfQbLmY&sz=w1000",
      },
      {
        name: "Harshita Suneja",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1wHnTAFA3aAUhVwHT5WbHUOTrYVLzGO0p&sz=w1000",
      }
    ],
  },
    //Social Media and Publicity
  {
    teamName: "Social Media and Publicity",
    members: [
      {
        name: "Yatra Jain",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1Ghmnbw4Yxp3SBHwsvTvmIDmgTLUJIln1&sz=w1000",
      },
      {
        name: "Manya Dhingra",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1-jO06e_IbDhoi1CTZAVCKwytm4sTLbTC&sz=w1000",
      },
      {
        name: "Kajal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1OA1P5Na5CEp4H1r78dM07DfBJbTx7nYM&sz=w1000",
      },
      // {
      //   name: "Umair Ahmed",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Khushi Khanna",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1T0v6d8VF7ymUXmOn_9Y4Lj-OSdLfnqbs&sz=w1000",
      },
      {
        name: "Nidhi Verma",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1baNFpIj0jBkT3v8XSWU8NIPl0cNrh4Ya&sz=w1000",
      },
      // {
      //   name: "Shreya Ojha",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Suhani",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1UgmjDg8fJUYNEQc1ovOfgrw5Dao2Ohm_&sz=w1000",
      },
      {
        name: "Sumit Maindoliya",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1a7P9J1YftTc62p3_5nS9xrtMUDVGfqzO&sz=w1000",
      },
      {
        name: "Khushi Tiwari",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=176nKtxJp-9ITFUr4gKurBmtsG0s7Q2Nl&sz=w1000",
      },
      {
        name: "Akshita Sachdeva",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1iz0VNZZpZvw_2Eewcz6_7tunfACyuRtQ&sz=w1000"
      },
      {
        name: "Simran Kaushal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1o2tHXURH_Drtd4W05C_cuIukMik61uiq&sz=w1000",
      },
      {
        name: "Siddhant Mahapatra",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1V9kcKswZ-JUMxsx7dwjAup4jVhXccxdf&sz=w1000",
      },
      {
        name: "Ayush Ranjan",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1wKngfvAVZnBUCnCnAWP4JiUd5O6JWau9&sz=w1000",
      },
      {
        name: "Anshul Gupta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1Wa72MhfU6-ARUHocogWaIwj4wF6ZA0OA&sz=w1000",
      },
      {
        name: "Harsh Raj",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1g5KtuzoZyuk_Rg4Oiw0z6hzyFYf1TqZs&sz=w1000",
      }
    ],
  },
    //Design and Creativity
  {
    teamName: "Design and Creativity",
    members: [
      {
        name: "Kashish Tyagi",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1p1GmyycdYa5fAGq7D41VfTDcnA_pzmfA&sz=w1000",
      },
      {
        name: "Kesar Bansal",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1M-C_5ks52f0vBoxHOrrC2oljkqanNvZD&sz=w1000",
      },
      {
        name: "Vidit Garg",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1i6r6hkZ731gZiIDb4hdY1EkM3aFKBO0v&sz=w1000",
      },
      {
        name: "Md Saif",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=12myjQHnZ01g9BXTBUjVaDrP-pxHt7Cpm&sz=w1000",
      },
      {
        name: "Harshit Gupta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1I_DyLdef6rJpel9KbBtdGi-qyFew1Wd1&sz=w1000",
      },
      {
        name: "Raghav Gupta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1kwM53H30sbDGrrhxvH8iYn3EBY7FqIYW&sz=w1000",
      },
      // {
      //   name: "Avinash Gola",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Naman Arora",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1A2FoW8rYwM4Erl2wj8GnqVlgCZmJLJ7d&sz=w1000",
      },
      {
        name: "Harsh Sharma",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1wBVODWBKmwjWtWmxHKNNjt4tFC7hcPuc&sz=w1000",
      },
      {
        name: "Lavanya Goyal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1LUO8KWL53GDO67EplW26waJeuZNZcX8A&sz=w1000",
      },
      {
        name: "Nikhil Tyagi",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1lA-icQbDB838uIeJp4jiN2IXaxwKXdtg&sz=w1000",
      },
      {
        name: "Kalpit Goyal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=19ZAm6CBzqMqbJIOscf_Jdb8AoWF0ZnsS&sz=w1000",
      }
    ],
  },
    //Video Editing
  {
    teamName: "Video Editing",
    members: [
      {
        name: "Himanshu Gupta",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1heshrNJ9YxtXAcDCOTwdcYDyi5-erAnL&sz=w1000",
      },
      // {
      //   name: "Samyak Patil",
      //   designation: "Head",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Yash Verma",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1cj4-2upsgPdfGg_AAbjmHkbjNGz4J7lU&sz=w1000",
      },
      {
        name: "Abhishek Kumar",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1QVH_--65da3OeC2YnsVccfTPU_l0NI3h&sz=w1000",
      },
      {
        name: "Saptarshi Pandit",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1LF0pwktVY8AY_T2_XL0qrMmMAVCNdzC1&sz=w1000",
      },
      {
        name: "Pabitra Mondal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1gUh8GAUFCvjJNmcvwo4AKwjzLOGKzg5Y&sz=w1000",
      },
      // {
      //   name: "Nikhil Kaushal",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Raghav Bisht",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1zRDlOahIh0bF7U1Yl62hMI48DUc8SlT3&sz=w1000",
      },
      {
        name: "Asmit Patel",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1plQSJr9A2-r2YTLzWZJAcz8uj1oR3HE6&sz=w1000",
      },
      {
        name: "Parikshit Singh",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1NOdqI-q64A0Eyls1ZHVkfmxopQWiLZ2n&sz=w1000",
      },
      {
        name: "Vinayak",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1k7Zyjb1Fn1cWjem0iwjtJEPRrmHdXWRB&sz=w1000",
      },
      {
        name: "Dhananjay Aggarwal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1xuMJE6s7A_wML-shSOdUoOo02GF0XX-A&sz=w1000",
      }
    ],
  },
    //Event Management
  {
    teamName: "Event Management",
    members: [
      {
        name: "Bhavik Aggarwal",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1WdI73uQR7hseQH9nKucdDaj0BsenB6ar&sz=w1000",
      },
      {
        name: "Taniket Singh",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1-5f3CW8EHjmJoGvuxegaBvMt63OkRQ11&sz=w1000",
      },
      {
        name: "Riddhi Bansal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=15r6r43Wr03lQ01JZcBuRntkWa4X8DZjg&sz=w1000",
      },
      {
        name: "Yashika Gandhi",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1NUijT6pgA4U2lqyY6r0LYqxOlrJ_v7Xo&sz=w1000",
      },
      {
        name: "Varun Kaushik",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1pR0wnjubK5WLx_GHGF2_G2F5rM_khlHd&sz=w1000",
      },
      {
        name: "Shaurya Gupta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=19SocUW0H4JKhOjgumUfE_P9ntX1YA5ze&sz=w1000",
      },
      {
        name: "Rudra Oberoi",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1GL74ZLsBFNn6AGE4iq2Y9d_vY2CJE0k6&sz=w1000",
      },
      {
        name: "Pranav Pratosh Sharma",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=13z2nfznr4XKEpsEwEnkQpo-WU7-xMKxN&sz=w1000",
      },
      {
        name: "Ishika Bindal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1Mxqqxza7iHDr63qCi5VBySAwFn2Uuw9u&sz=w1000",
      },
      {
        name: "Faraz Ahmed Qureshi",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1bX0SQEI7ywUXRgtEgvjFdgUYsZmOAyVd&sz=w1000",
      },
      // {
      //   name: "Himanshu Kumar",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Vansh Tandon",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1a4UVgZDQBSqBSfk4RCmQ9sUc3K7BfIMD&sz=w1000",
      },
      // {
      //   name: "Sahil Sharma",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      // {
      //   name: "Mohit Pal",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Ayush Singh",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1_swoavpak1btFkyK2Cs0bKIfmzG33K-W&sz=w1000",
      },
      {
        name: "Shounak Dua",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1NixCIvxWe4-iuGG5ub4UZtCHQ6EEzCi6&sz=w1000",
      },
      {
        name: "Ritesh Kumar Tiwari",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1SwHtS-L7UgXMJ_EQGlXSpWkMJ_RxsEQo&sz=w1000",
      },
      {
        name: "Ayush Ramola",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1OpSVKxiVg8cAy4GXjXF7iHt0hfm0Sm20&sz=w1000",
      },
      {
        name: "Madhav Bhardawaj",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1CmcTJ1KKm8oAA5zqlTjwIse_vxDxtC7A&sz=w1000",
      },
      {
        name: "Tanuj Singh Rawat",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1kFRpVKPpNlu4muRy9LfOFaA2vQmXJ0hl&sz=w1000",
      },
      {
        name: "Mohit Bansal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1eWEhgPuW-ubvWpa6H_x0GrGapaccDCwc&sz=w1000",
      },
      {
        name: "Sonvi Goyal",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=11fzMk83g-jn-25MtsYzY1FbzZY12npNV&sz=w1000",
      },
      {
        name: "Pawan Gupta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=11YlG_ReaCZoe00HrmU4F9rQJQoER0KOU&sz=w1000",
      },
      {
        name: "Devansh Verma",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=174almMZfcnv4AFNYOtx4PLyd2wfY9x3g&sz=w1000",
      },
      {
        name: "Nishant Kumar",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1GVv6w-x0c6xe4c63Pfdy_DMD9vIaGG0D&sz=w1000",
      }
    ],
  },
    //Sponsorship and Outreach
  {
    teamName: "Sponsorship and Outreach",
    members: [
      {
        name: "Khushi Agarwal",
        designation: "Head",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1iyIMt0f-FU2WuWN0HIpNugPaOlPM0Q-u&sz=w1000",
      },
      // {
      //   name: "Yash Tharani",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      // {
      //   name: "Bhavya",
      //   designation: "Executive",
      //   linkedin: "",
      //   instagram: "",
      //   optionalLink: "",
      //   picLink: "",
      // },
      {
        name: "Aditya Yadav",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1Ika_LBKnw3k_BQB9SmFUrgeHrw2uM4uS&sz=w1000"
      },
      {
        name: "Tanzil Jain",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1bnhlODrEFlEySNnUAP1jq2NtY0jhvPkQ&sz=w1000"
      },
      {
        name: "Tanmay Jain",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1JjkGSblhu8xGfnuwcjVai1YokBR9FJj7&sz=w1000",
      },
      {
        name: "Harshit Mehta",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1Pz1A6XCauitYvNIXcyngS-_Ic_ko4YJG&sz=w1000"
      },
      {
        name: "Pratham Sikka",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1VGrEgDSDctRvUuuJ2nBlZaWPAe0yCZpC&sz=w1000",
      },
      {
        name: "Lakshay Jain",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1pRz60SqFOs2v5OlBq0Q6jlVEbr-pjgNW&sz=w1000",
      },
      {
        name: "Riyanshu",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1YNOe6-_KP8eXFVRom3VVKvg3HD-25VL0&sz=w1000",
      },
      {
        name: "Deepanshu Yadav",
        designation: "Executive",
        linkedin: "",
        instagram: "",
        optionalLink: "",
        picLink: "https://drive.google.com/thumbnail?id=1vB5tXqqZv7TkQI54MeBuegrsigFQGgx-&sz=w1000",
      }
    ],
  }

  // Add more teams here...
];

export default teams;
